version: '3.4'
services:
  web: 
    build: 
      context: ./web
      dockerfile: Dockerfile
    command: 'npm start'
    volumes:
      - ./web:/usr/src/app
    ports:
      - "3000:3000"
  plumber:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: 'Rscript plumberServer.R'
    volumes:
      - ./server:/usr/local/src/plumber
    # restart: always
    ports:
      - "8000:8000"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #     delay: 5s
    #     max_attempts: 3
    #     window: 120s