version: '3.4'
services:
  plumber:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports: 
      - "3000:6379"